import { Product } from "./types";

export const products: Product[] = [
  // ── Yeni Ürünler (Mayıs 2026) ─────────────────────────────────
  {
    id: "b-005",
    slug: "eclat-pirlanta-bileklik",
    name: "Éclat Pırlanta Bileklik",
    category: "Bileklikler",
    categorySlug: "bileklikler",
    price: 145000,
    priceFormatted: "₺145.000",
    shortDescription: "18K beyaz altın üzeri tam tur pavé pırlanta kadın bileklik.",
    description:
      "Éclat, Fransızcada 'parıltı' demektir. Beyaz altın üzerinde çepeçevre akan pavé pırlantalar; gün ışığında, mum ışığında, her ışıkta aynı büyüyü yaratır. Günlük şıklığın vazgeçilmez tamamlayıcısı.",
    images: [
      { src: "/images/products/eclat-pirlanta-bileklik/1.png", alt: "Éclat pırlanta bileklik" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Doğal Pırlanta" },
      { label: "Yerleştirme", value: "Pavé" },
      { label: "Renk", value: "E–F" },
      { label: "Saflık", value: "VS1–VS2" },
    ],
    certificateInfo: [
      { label: "Sertifika Kurumu", value: "IGI" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Beyaz Altın (18K)" },
      { label: "Uzunluk", value: "18 cm" },
    ],
    materials: ["18K Beyaz Altın", "Pırlanta"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "set-004",
    slug: "dore-altin-set",
    name: "Doré Altın Set",
    category: "Setler",
    categorySlug: "setler",
    price: 195000,
    priceFormatted: "₺195.000",
    shortDescription: "Uyumlu altın parçalardan oluşan zarif kadın seti.",
    description:
      "Doré; altının en saf tonunu, birbiriyle uyum içinde tasarlanmış parçalarla sunar. Tek başına ya da bir arada giyildiğinde aynı bütünlük ve zarafet hissi. Özel kutusunda hediye olarak sunulabilir.",
    images: [
      { src: "/images/products/dore-altin-set/1.png", alt: "Doré altın set, tam görünüm" },
      { src: "/images/products/dore-altin-set/6.png", alt: "Doré altın set, detay" },
      { src: "/images/products/dore-altin-set/7.png", alt: "Doré altın set, detay 2" },
      { src: "/images/products/dore-altin-set/8.png", alt: "Doré altın set, detay 3" },
    ],
    stoneSpecs: [
      { label: "Set İçeriği", value: "Uyumlu altın parçalar" },
    ],
    certificateInfo: [
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
    ],
    materials: ["18K Sarı Altın"],
    tags: ["set", "altin", "Kadın"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "k-005",
    slug: "dore-altin-kolye",
    name: "Doré Altın Kolye",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 89000,
    priceFormatted: "₺89.000",
    shortDescription: "18K sarı altın zarif kadın kolye.",
    description:
      "Altının en saf ifadesi: ince işçilik ve 18 ayar sarı altının sıcak parıltısıyla hayat bulan Doré Kolye, her dekoltede ayrı bir anlam kazanır. Sadeliğin kendisi de bir mücevherdir.",
    images: [
      { src: "/images/products/dore-altin-kolye/1.png", alt: "Doré altın kolye" },
      { src: "/images/products/dore-altin-kolye/11.png", alt: "Doré altın kolye, detay" },
      { src: "/images/products/dore-altin-kolye/12.png", alt: "Doré altın kolye, detay 2" },
    ],
    stoneSpecs: [],
    certificateInfo: [
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
      { label: "Zincir Uzunluğu", value: "42 cm (ayarlanabilir)" },
    ],
    materials: ["18K Sarı Altın"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "e-005",
    slug: "fleur-renkli-tas-kupe",
    name: "Fleur Renkli Taş Küpe",
    category: "Küpeler",
    categorySlug: "kupeler",
    price: 78000,
    priceFormatted: "₺78.000",
    shortDescription: "Renkli taş detaylı 18K altın kadın küpe.",
    description:
      "Fleur koleksiyonu, doğanın en canlı renklerini kuyuma taşır. Renkli taşların coşkusu ve altının sıcaklığı bir arada; her hareketle yüzünüze yeni bir renk yansır.",
    images: [
      { src: "/images/products/fleur-renkli-tas-kupe/1.png", alt: "Fleur renkli taş küpe" },
      { src: "/images/products/fleur-renkli-tas-kupe/13.png", alt: "Fleur küpe, detay" },
      { src: "/images/products/fleur-renkli-tas-kupe/15.png", alt: "Fleur küpe, detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Renkli Taş" },
    ],
    certificateInfo: [
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı/Beyaz Altın (18K)" },
    ],
    materials: ["18K Altın", "Renkli Taş"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "b-006",
    slug: "or-fin-altin-bileklik",
    name: "Or Fin Altın Bileklik",
    category: "Bileklikler",
    categorySlug: "bileklikler",
    price: 72000,
    priceFormatted: "₺72.000",
    shortDescription: "18K sarı altın ince zincir kadın bileklik.",
    description:
      "Or Fin, sadeliğin gücüne inanır. 18 ayar sarı altının sıcak tonları, ince ve akışkan zincir formunda bileğinize dolanır. Herkese yakışan, her tarza uyum sağlayan zarif bir klasik.",
    images: [
      { src: "/images/products/or-fin-altin-bileklik/1.png", alt: "Or Fin altın bileklik" },
      { src: "/images/products/or-fin-altin-bileklik/2.png", alt: "Or Fin bileklik, detay" },
      { src: "/images/products/or-fin-altin-bileklik/3.png", alt: "Or Fin bileklik, detay 2" },
    ],
    stoneSpecs: [],
    certificateInfo: [
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
      { label: "Uzunluk", value: "17 cm + 3 cm uzatma" },
    ],
    materials: ["18K Sarı Altın"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "ex-005",
    slug: "celeste-exclusive-bileklik",
    name: "Céleste Bileklik",
    category: "Exclusive",
    categorySlug: "exclusive",
    price: 485000,
    priceFormatted: "₺485.000",
    shortDescription: "Özel tasarım nadir taşlı exclusive kadın bileklik. Sınırlı üretim.",
    description:
      "Céleste; gökyüzünün derinliğinden ilham alır. Her detayı usta eller tarafından elle işlenmiş bu exclusive bileklik, yalnızca seçkin taşlar ve atölye ustalığıyla hayat bulur. Dünyada sınırlı sayıda üretilen, kalıcı bir eser.",
    images: [
      { src: "/images/products/celeste-bileklik/1.png", alt: "Céleste exclusive bileklik" },
      { src: "/images/products/celeste-bileklik/21.png", alt: "Céleste exclusive bileklik, detay" },
      { src: "/images/products/celeste-bileklik/22.png", alt: "Céleste exclusive bileklik, detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Nadir Renkli Taş" },
      { label: "Metal", value: "Platin / 18K Altın" },
    ],
    certificateInfo: [
      { label: "Sertifika", value: "Uluslararası Sertifikalı" },
      { label: "Üretim Adedi", value: "Sınırlı Üretim" },
    ],
    karatDetails: [
      { label: "Metal", value: "950 Platin" },
      { label: "Uzunluk", value: "18 cm" },
    ],
    materials: ["950 Platin", "Nadir Taş"],
    gender: ["Kadın"],
    isExclusive: true,
    limitedPieces: 5,
    isNew: true,
  },
  {
    id: "k-006",
    slug: "fleur-renkli-tas-kolye",
    name: "Fleur Renkli Taş Kolye",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 115000,
    priceFormatted: "₺115.000",
    shortDescription: "Renkli taş detaylı 18K altın kadın kolye.",
    description:
      "Fleur Kolye, renkli taşların coşkusunu boyun hattınıza taşır. Her taş seçilmiş bir anı simgeler; altının sıcaklığı onları birbirine bağlayarak tutarlı bir şiir oluşturur.",
    images: [
      { src: "/images/products/fleur-renkli-tas-kolye/1.png", alt: "Fleur renkli taş kolye" },
      { src: "/images/products/fleur-renkli-tas-kolye/24.png", alt: "Fleur kolye, detay" },
      { src: "/images/products/fleur-renkli-tas-kolye/25.png", alt: "Fleur kolye, detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Renkli Taş" },
    ],
    certificateInfo: [
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı/Beyaz Altın (18K)" },
      { label: "Zincir Uzunluğu", value: "42 cm (ayarlanabilir)" },
    ],
    materials: ["18K Altın", "Renkli Taş"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "k-007",
    slug: "vera-pirlanta-kolye",
    name: "Vera Pırlanta Kolye",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 215000,
    priceFormatted: "₺215.000",
    shortDescription: "Özel tasarım pırlanta 18K altın kadın kolye.",
    description:
      "Vera, 'gerçek' ve 'saf' anlamına gelir. Tasarım pırlantalar ve altının saf parıltısıyla hayat bulan bu kolye, her detayında bir özen ve özgünlük taşır. Zamansız bir şıklık ifadesi.",
    images: [
      { src: "/images/products/vera-pirlanta-kolye/1.png", alt: "Vera pırlanta kolye" },
      { src: "/images/products/vera-pirlanta-kolye/26.png", alt: "Vera kolye, detay" },
      { src: "/images/products/vera-pirlanta-kolye/28.png", alt: "Vera kolye, detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Doğal Pırlanta" },
      { label: "Kesim", value: "Tasarım Kesim" },
      { label: "Renk", value: "E–F" },
      { label: "Saflık", value: "VS1–VS2" },
    ],
    certificateInfo: [
      { label: "Sertifika Kurumu", value: "IGI / GIA" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
      { label: "Zincir Uzunluğu", value: "42 cm" },
    ],
    materials: ["18K Sarı Altın", "Pırlanta"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "b-007",
    slug: "exo-pirlanta-bileklik",
    name: "Exo Pırlanta Bileklik",
    category: "Bileklikler",
    categorySlug: "bileklikler",
    price: 178000,
    priceFormatted: "₺178.000",
    shortDescription: "Özel tasarım pırlanta 18K altın kadın bileklik.",
    description:
      "Exo, sınırları aşan bir tasarım anlayışını temsil eder. Pırlantaların olağandışı dizilimi ve altının kusursuz işçiliğiyle hazırlanan bu bileklik, her bileğe bağımsız bir kimlik katar.",
    images: [
      { src: "/images/products/exo-pirlanta-bileklik/1.png", alt: "Exo pırlanta bileklik" },
      { src: "/images/products/exo-pirlanta-bileklik/30.png", alt: "Exo bileklik, detay" },
      { src: "/images/products/exo-pirlanta-bileklik/31.png", alt: "Exo bileklik, detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Doğal Pırlanta" },
      { label: "Kesim", value: "Tasarım Kesim" },
      { label: "Renk", value: "E–F" },
      { label: "Saflık", value: "VS1–VS2" },
    ],
    certificateInfo: [
      { label: "Sertifika Kurumu", value: "IGI / GIA" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
      { label: "Uzunluk", value: "18 cm" },
    ],
    materials: ["18K Sarı Altın", "Pırlanta"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "h-006",
    slug: "bleu-pirlanta-yuzuk",
    name: "Bleu Pırlanta Yüzük",
    category: "Yüzükler",
    categorySlug: "halkalar",
    price: 135000,
    priceFormatted: "₺135.000",
    shortDescription: "Özel tasarım pırlanta 18K altın kadın yüzük.",
    description:
      "Bleu, doğanın en sakin ve en derin tonundan ilham alır. Bu özel tasarım pırlanta yüzük; mavi bir anın sonsuzluğunu parmağınıza taşır. İnce işçilik ve seçkin pırlantalarla hazırlanan, zamansız bir imza.",
    images: [
      { src: "/images/products/bleu-pirlanta-yuzuk/1.png", alt: "Bleu pırlanta yüzük" },
      { src: "/images/products/bleu-pirlanta-yuzuk/32.png", alt: "Bleu yüzük, detay" },
      { src: "/images/products/bleu-pirlanta-yuzuk/34.png", alt: "Bleu yüzük, detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Doğal Pırlanta" },
      { label: "Kesim", value: "Tasarım Kesim" },
      { label: "Renk", value: "E–F" },
      { label: "Saflık", value: "VS1–VS2" },
    ],
    certificateInfo: [
      { label: "Sertifika Kurumu", value: "IGI / GIA" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
      { label: "Yüzük Bedeni", value: "52 (özel boyda üretilebilir)" },
    ],
    materials: ["18K Sarı Altın", "Pırlanta"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "inci-007",
    slug: "perle-inci-kolye",
    name: "Perle İnci Kolye",
    category: "İnci",
    categorySlug: "inci",
    price: 98000,
    priceFormatted: "₺98.000",
    shortDescription: "İnci detaylı 18K altın kadın kolye.",
    description:
      "Perle, sadeliğin en değerli hali. İncinin kadim zarafeti ve altının sıcaklığıyla hazırlanan bu kolye; doğanın en özel hediyesini modern ve arınmış bir silüette sunar.",
    images: [
      { src: "/images/products/perle-inci-kolye/1.png", alt: "Perle inci kolye" },
      { src: "/images/products/perle-inci-kolye/36.png", alt: "Perle inci kolye, detay" },
      { src: "/images/products/perle-inci-kolye/37.png", alt: "Perle inci kolye, detay 2" },
    ],
    stoneSpecs: [
      { label: "İnci Türü", value: "Kültür İnci" },
      { label: "Parlaklık", value: "Yüksek" },
    ],
    certificateInfo: [
      { label: "Kalite Belgesi", value: "GIA Pearl Grading" },
    ],
    karatDetails: [
      { label: "Metal", value: "18K Altın" },
      { label: "Uzunluk", value: "42 cm (ayarlanabilir)" },
    ],
    materials: ["18K Altın", "İnci"],
    tags: ["inci", "luster-yuksek", "Kadın"],
    gender: ["Kadın"],
    isNew: true,
  },
  {
    id: "b-008",
    slug: "etoile-altin-bileklik",
    name: "Étoile Altın Bileklik",
    category: "Bileklikler",
    categorySlug: "bileklikler",
    price: 85000,
    priceFormatted: "₺85.000",
    shortDescription: "18K sarı altın zarif kadın bileklik.",
    description:
      "Étoile, gece gökyüzünün en parlak yıldızından ilham alır. 18 ayar sarı altının sıcaklığında işlenmiş zarif bir form: her bakışta yeniden keşfedilen, bileğinize asılan bir ışık.",
    images: [
      { src: "/images/products/etoile-altin-bileklik/1.png", alt: "Étoile altın bileklik" },
      { src: "/images/products/etoile-altin-bileklik/17.png", alt: "Étoile bileklik, detay" },
      { src: "/images/products/etoile-altin-bileklik/18.png", alt: "Étoile bileklik, detay 2" },
      { src: "/images/products/etoile-altin-bileklik/19.png", alt: "Étoile bileklik, detay 3" },
    ],
    stoneSpecs: [],
    certificateInfo: [
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
      { label: "Uzunluk", value: "17 cm + 3 cm uzatma" },
    ],
    materials: ["18K Sarı Altın"],
    gender: ["Kadın"],
    isNew: true,
  },

  // ── Anneler Günü Doğal Taş Koleksiyonu ───────────────────────
  {
    id: "k-008",
    slug: "larvikite-midnight-aura",
    name: "Larvikite Midnight Aura",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 9900,
    priceFormatted: "₺9.900",
    originalPrice: 18900,
    originalPriceFormatted: "₺18.900",
    isMothersDay: true,
    shortDescription: "Siyah labradorit doğal taş, 14K altın zincir kolye. Anneler Günü özel.",
    description:
      "Larvikite — ya da siyah labradorit — yüzeyi boyunca akan metalik parıltılarıyla gecenin karanlığını içinde taşır. Gri-siyah mat dokusu ve adeta yıldız parçacıklarından oluşan o eşsiz ışık oyunuyla hem gizemli hem de sofistike bir derinlik sunar. 14K altın zinciriyle sunulan bu kolye, annenizin her gün taşımak isteyeceği özel bir parçadır.",
    images: [
      { src: "/images/products/Larvikite Midnight Aura/1.png", alt: "Larvikite Midnight Aura kolye" },
      { src: "/images/products/Larvikite Midnight Aura/5.png", alt: "Larvikite detay görünüm" },
      { src: "/images/products/Larvikite Midnight Aura/6.png", alt: "Larvikite detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Larvikit (Siyah Labradorit — Doğal)" },
      { label: "Renk", value: "Gri-Siyah, Metalik Parıltı" },
      { label: "Karakter", value: "Mat Doku, İçsel Işık Oyunu" },
      { label: "Kesim", value: "Oval Kabochon" },
      { label: "Boyut", value: "12 × 16 mm (yaklaşık)" },
    ],
    certificateInfo: [
      { label: "Taş Menşei", value: "Norveç (Larvik Bölgesi)" },
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "585 Sarı/Beyaz/Rose Altın (14K)" },
      { label: "Zincir Uzunluğu", value: "42 cm (ayarlanabilir)" },
      { label: "Zincir Seçimi", value: "Sarı Altın · Beyaz Altın · Rose Altın" },
    ],
    materials: ["14K Altın", "Larvikit Doğal Taş"],
    tags: ["dogal-tas", "kolye", "anneler-gunu", "Kadın"],
    gender: ["Kadın"],
    isNew: true,
    chainOptions: [
      { value: "beyaz-altin", label: "Beyaz Altın" },
      { value: "rose-altin", label: "Rose Altın" },
      { value: "sari-altin", label: "Sarı Altın" },
    ],
  },
  {
    id: "k-009",
    slug: "lemon-quartz-sunbeam-drop",
    name: "Lemon Quartz Sunbeam Drop",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 9900,
    priceFormatted: "₺9.900",
    originalPrice: 18900,
    originalPriceFormatted: "₺18.900",
    isMothersDay: true,
    shortDescription: "Limon kuvars doğal taş, 14K altın zincir kolye. Anneler Günü özel.",
    description:
      "Limon Kuvars, adeta sabah güneşini dondurup boynunuza asmak gibidir. Berrak, kristal yapısı ve açık sarı-yeşil tonları taze, enerjik ve tam anlamıyla modern bir duruş sergiler. Güneşin ilk ışınlarını andıran bu taş, annenizin her güne mutlu başlamasına eşlik eder.",
    images: [
      { src: "/images/products/Lemon Quartz Sunbeam Drop/1.png", alt: "Lemon Quartz Sunbeam Drop kolye" },
      { src: "/images/products/Lemon Quartz Sunbeam Drop/8.png", alt: "Lemon Quartz detay görünüm" },
      { src: "/images/products/Lemon Quartz Sunbeam Drop/9.png", alt: "Lemon Quartz detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Limon Kuvars (Lemon Quartz — Doğal)" },
      { label: "Renk", value: "Açık Sarı-Yeşil, Berrak" },
      { label: "Karakter", value: "Taze, Enerjik, Şeffaf" },
      { label: "Kesim", value: "Damla (Briolette)" },
      { label: "Boyut", value: "10 × 14 mm (yaklaşık)" },
    ],
    certificateInfo: [
      { label: "Taş Sınıfı", value: "AAA Doğal Kuvars" },
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "585 Sarı/Beyaz/Rose Altın (14K)" },
      { label: "Zincir Uzunluğu", value: "42 cm (ayarlanabilir)" },
      { label: "Zincir Seçimi", value: "Sarı Altın · Beyaz Altın · Rose Altın" },
    ],
    materials: ["14K Altın", "Limon Kuvars Doğal Taş"],
    tags: ["dogal-tas", "kolye", "anneler-gunu", "Kadın"],
    gender: ["Kadın"],
    isNew: true,
    chainOptions: [
      { value: "beyaz-altin", label: "Beyaz Altın" },
      { value: "rose-altin", label: "Rose Altın" },
      { value: "sari-altin", label: "Sarı Altın" },
    ],
  },
  {
    id: "k-010",
    slug: "royal-garnet-crimson-petal",
    name: "Royal Garnet Crimson Petal",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 9900,
    priceFormatted: "₺9.900",
    originalPrice: 18900,
    originalPriceFormatted: "₺18.900",
    isMothersDay: true,
    shortDescription: "Granat doğal taş, 14K altın zincir kolye. Anneler Günü özel.",
    description:
      "Granat — kışın ortasında açan koyu kırmızı bir gül gibidir. Derin ve tutkulu kırmızı tonuyla zamansız bir asaletin ve klasik lüksün simgesidir. Yüzyıllardır kraliyet mücevherlerinde baş köşeyi süsleyen granat, annenize hem anlam hem de güzellik sunar.",
    images: [
      { src: "/images/products/Royal Garnet Crimson Petal/1.png", alt: "Royal Garnet Crimson Petal kolye" },
      { src: "/images/products/Royal Garnet Crimson Petal/10.png", alt: "Garnet detay görünüm" },
      { src: "/images/products/Royal Garnet Crimson Petal/11.png", alt: "Garnet detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Granat / Garnet (Doğal)" },
      { label: "Renk", value: "Derin Kırmızı (Crimson)" },
      { label: "Karakter", value: "Zamansız, Asil, Tutkulu" },
      { label: "Kesim", value: "Yuvarlak Faceted" },
      { label: "Boyut", value: "8 mm çap (yaklaşık)" },
    ],
    certificateInfo: [
      { label: "Taş Menşei", value: "Doğal, Isıl İşlemsiz" },
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "585 Sarı/Beyaz/Rose Altın (14K)" },
      { label: "Zincir Uzunluğu", value: "42 cm (ayarlanabilir)" },
      { label: "Zincir Seçimi", value: "Sarı Altın · Beyaz Altın · Rose Altın" },
    ],
    materials: ["14K Altın", "Granat Doğal Taş"],
    tags: ["dogal-tas", "kolye", "anneler-gunu", "Kadın"],
    gender: ["Kadın"],
    isNew: true,
    chainOptions: [
      { value: "beyaz-altin", label: "Beyaz Altın" },
      { value: "rose-altin", label: "Rose Altın" },
      { value: "sari-altin", label: "Sarı Altın" },
    ],
  },
  {
    id: "k-011",
    slug: "paraiba-blue-vitality-drop",
    name: "Paraiba Blue Vitality Drop",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 9900,
    priceFormatted: "₺9.900",
    originalPrice: 18900,
    originalPriceFormatted: "₺18.900",
    isMothersDay: true,
    shortDescription: "Paraiba kuvars doğal taş, 14K altın zincir kolye. Anneler Günü özel.",
    description:
      "Paraiba Kuvars, tropikal denizlerin en berrak sularından fırlamış gibidir. Canlı turkuaz rengiyle dikkat çekici bir modernlik yayar; bu taş sadece bir mücevher değil, taşıyan kişinin enerjisini ve canlılığını yansıtan bir ifadedir. Annenizi her baktığında gülümsetecek bir armağan.",
    images: [
      { src: "/images/products/Paraiba Blue Vitality Drop/1.png", alt: "Paraiba Blue Vitality Drop kolye" },
      { src: "/images/products/Paraiba Blue Vitality Drop/14.png", alt: "Paraiba kuvars detay görünüm" },
      { src: "/images/products/Paraiba Blue Vitality Drop/15.png", alt: "Paraiba kuvars detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Apatit / Paraiba Kuvars (Doğal)" },
      { label: "Renk", value: "Canlı Turkuaz-Mavi" },
      { label: "Karakter", value: "Tropikal Enerji, Modern, Canlı" },
      { label: "Kesim", value: "Damla (Pear Faceted)" },
      { label: "Boyut", value: "9 × 12 mm (yaklaşık)" },
    ],
    certificateInfo: [
      { label: "Taş Sınıfı", value: "Doğal, A Kalite" },
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "585 Sarı/Beyaz/Rose Altın (14K)" },
      { label: "Zincir Uzunluğu", value: "42 cm (ayarlanabilir)" },
      { label: "Zincir Seçimi", value: "Sarı Altın · Beyaz Altın · Rose Altın" },
    ],
    materials: ["14K Altın", "Paraiba Kuvars Doğal Taş"],
    tags: ["dogal-tas", "kolye", "anneler-gunu", "Kadın"],
    gender: ["Kadın"],
    isNew: true,
    chainOptions: [
      { value: "beyaz-altin", label: "Beyaz Altın" },
      { value: "rose-altin", label: "Rose Altın" },
      { value: "sari-altin", label: "Sarı Altın" },
    ],
  },
  {
    id: "k-012",
    slug: "celestial-sunstone-glow",
    name: "Celestial Sunstone Glow",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 9900,
    priceFormatted: "₺9.900",
    originalPrice: 18900,
    originalPriceFormatted: "₺18.900",
    isMothersDay: true,
    shortDescription: "Güneş taşı doğal taş, 14K altın zincir kolye. Anneler Günü özel.",
    description:
      "Güneş Taşı (Sunstone), adını olağanüstü optik özelliğinden alır: içindeki doğal metalik parıltılar (aventuresans) her hareketle farklı bir ışık oyunu yaratır. Sıcak, samimi ve ışıltılı karakteri; anneler için yaratılmış gibidir. Her gün taşıması için tasarlanmış bir güneş parçası.",
    images: [
      { src: "/images/products/Celestial Sunstone Glow/1.png", alt: "Celestial Sunstone Glow kolye" },
      { src: "/images/products/Celestial Sunstone Glow/17.png", alt: "Sunstone detay görünüm" },
      { src: "/images/products/Celestial Sunstone Glow/18.png", alt: "Sunstone detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Güneş Taşı / Sunstone (Doğal)" },
      { label: "Renk", value: "Sıcak Turuncu-Altın, Aventuresans Parıltı" },
      { label: "Karakter", value: "Işıltılı, Sıcak, Samimi" },
      { label: "Kesim", value: "Yuvarlak Kabochon" },
      { label: "Boyut", value: "10 mm çap (yaklaşık)" },
    ],
    certificateInfo: [
      { label: "Taş Menşei", value: "Oregon/Hindistan (Doğal Sunstone)" },
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "585 Sarı/Beyaz/Rose Altın (14K)" },
      { label: "Zincir Uzunluğu", value: "42 cm (ayarlanabilir)" },
      { label: "Zincir Seçimi", value: "Sarı Altın · Beyaz Altın · Rose Altın" },
    ],
    materials: ["14K Altın", "Güneş Taşı Doğal Taş"],
    tags: ["dogal-tas", "kolye", "anneler-gunu", "Kadın"],
    gender: ["Kadın"],
    isNew: true,
    chainOptions: [
      { value: "beyaz-altin", label: "Beyaz Altın" },
      { value: "rose-altin", label: "Rose Altın" },
      { value: "sari-altin", label: "Sarı Altın" },
    ],
  },
  {
    id: "k-013",
    slug: "emerald-eternal-verdant-luxe",
    name: "Emerald Eternal Verdant Luxe",
    category: "Kolyeler",
    categorySlug: "kolyeler",
    price: 9900,
    priceFormatted: "₺9.900",
    originalPrice: 18900,
    originalPriceFormatted: "₺18.900",
    isMothersDay: true,
    shortDescription: "Zümrüt rengi doğal taş, 14K altın zincir kolye. Anneler Günü özel.",
    description:
      "Zümrüt yeşili, kadim zamanlardan bu yana prestijin ve doğanın en berrak yansıması olmuştur. Emerald Eternal, zengin yeşil tonuyla koleksiyonun en yüksek prestijli parçalarından biridir. Annenize gerçek bir miras parçası gibi hissettiren bu kolye, doğal zümrüt taşının tüm ihtişamını günlük hayata taşır.",
    images: [
      { src: "/images/products/Emerald Eternal Verdant Luxe/1.png", alt: "Emerald Eternal Verdant Luxe kolye" },
      { src: "/images/products/Emerald Eternal Verdant Luxe/24.png", alt: "Zümrüt detay görünüm" },
      { src: "/images/products/Emerald Eternal Verdant Luxe/25.png", alt: "Zümrüt detay 2" },
    ],
    stoneSpecs: [
      { label: "Taş Türü", value: "Zümrüt / Emerald (Doğal)" },
      { label: "Renk", value: "Zengin Koyu Yeşil (Vivid Green)" },
      { label: "Karakter", value: "Prestijli, High-End, Zamansız" },
      { label: "Kesim", value: "Dikdörtgen Cabochon" },
      { label: "Boyut", value: "8 × 10 mm (yaklaşık)" },
    ],
    certificateInfo: [
      { label: "Taş Menşei", value: "Kolombiya veya Brezilya (Doğal)" },
      { label: "Garanti", value: "2 Yıl" },
    ],
    karatDetails: [
      { label: "Metal", value: "585 Sarı/Beyaz/Rose Altın (14K)" },
      { label: "Zincir Uzunluğu", value: "42 cm (ayarlanabilir)" },
      { label: "Zincir Seçimi", value: "Sarı Altın · Beyaz Altın · Rose Altın" },
    ],
    materials: ["14K Altın", "Zümrüt Doğal Taş"],
    tags: ["dogal-tas", "kolye", "anneler-gunu", "Kadın"],
    gender: ["Kadın"],
    isNew: true,
    chainOptions: [
      { value: "beyaz-altin", label: "Beyaz Altın" },
      { value: "rose-altin", label: "Rose Altın" },
      { value: "sari-altin", label: "Sarı Altın" },
    ],
  },

  // ── Bebek Özel — Emzik ────────────────────────────────────────
  {
    id: "bebek-emzik-001",
    slug: "altin-bebek-emzik-klasik",
    name: "Altın Bebek Emziği — Klasik",
    category: "Bebek Emzik",
    categorySlug: "bebek-ozel",
    tags: ["emzik"],
    price: 12500,
    priceFormatted: "₺12.500",
    shortDescription: "14 ayar sarı altın çerçeveli, hipoalerjenik silikonlu bebek emziği.",
    description: "Bebeğinizin ilk mücevheri. Nikel içermeyen 14 ayar sarı altın çerçeve; medikal grade, BPA içermeyen silikon uç ile birleşerek hem güvenli hem de zarif bir ilk dokunuş sunar. Her biri el yapımı, özel hediyelik kutusunda teslim edilir.",
    images: [
      { src: "https://images.unsplash.com/photo-1590080876351-941da357a4e4?w=800&q=80&fit=crop", alt: "Altın bebek emziği klasik" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Güvenlik", value: "CE & EN 1400 Sertifikalı" }],
    karatDetails: [
      { label: "Metal", value: "585 Sarı Altın (14K)" },
      { label: "Silikon", value: "BPA-free Medikal Grade" },
    ],
    materials: ["14K Sarı Altın", "Medikal Silikon"],
    isNew: true,
  },
  {
    id: "bebek-emzik-002",
    slug: "altin-bebek-emzik-pırlanta",
    name: "Altın Bebek Emziği — Pırlanta",
    category: "Bebek Emzik",
    categorySlug: "bebek-ozel",
    tags: ["emzik"],
    price: 24800,
    priceFormatted: "₺24.800",
    shortDescription: "18 ayar altın çerçeve, pavé pırlanta süslemeli bebek emziği.",
    description: "En özel anlara layık bir ilk mücevher. 18 ayar beyaz altın üzeri pavé yerleştirme ile dizilen doğal pırlantalar, çerçeveyi büyülü bir parıltıya dönüştürür. Doğum hediyeliği olarak da idealdir.",
    images: [
      { src: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80&fit=crop", alt: "Altın bebek emziği pırlanta" },
    ],
    stoneSpecs: [
      { label: "Taş", value: "Doğal Pırlanta" },
      { label: "Yerleştirme", value: "Pavé" },
    ],
    certificateInfo: [{ label: "Güvenlik", value: "CE & EN 1400 Sertifikalı" }],
    karatDetails: [
      { label: "Metal", value: "750 Beyaz Altın (18K)" },
      { label: "Silikon", value: "BPA-free Medikal Grade" },
    ],
    materials: ["18K Beyaz Altın", "Pırlanta", "Medikal Silikon"],
    isNew: true,
  },
  {
    id: "bebek-emzik-003",
    slug: "altin-bebek-emzik-rose",
    name: "Altın Bebek Emziği — Rose",
    category: "Bebek Emzik",
    categorySlug: "bebek-ozel",
    tags: ["emzik"],
    price: 14200,
    priceFormatted: "₺14.200",
    shortDescription: "14 ayar rose altın çerçeveli, nazar boncuğu detaylı bebek emziği.",
    description: "Rose altının sıcak tonları, üzerindeki minik mavi nazar boncuğu ile buluşarak bebeğinizi hem şıklık hem de uğurla kuşatır. El işçiliği, tek parça üretim.",
    images: [
      { src: "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800&q=80&fit=crop", alt: "Altın bebek emziği rose" },
    ],
    stoneSpecs: [
      { label: "Taş", value: "Mavi Mine (Nazar)" },
    ],
    certificateInfo: [{ label: "Güvenlik", value: "CE & EN 1400 Sertifikalı" }],
    karatDetails: [
      { label: "Metal", value: "585 Rose Altın (14K)" },
      { label: "Silikon", value: "BPA-free Medikal Grade" },
    ],
    materials: ["14K Rose Altın", "Mine", "Medikal Silikon"],
    isNew: true,
  },

  // ── Bebek Özel — Künye ────────────────────────────────────────
  {
    id: "bebek-kunye-001",
    slug: "altin-bebek-kunye-duz",
    name: "Altın Bebek Künyesi — Düz",
    category: "Bebek Künye",
    categorySlug: "bebek-ozel",
    tags: ["kunye"],
    price: 8900,
    priceFormatted: "₺8.900",
    shortDescription: "14 ayar altın, kişiselleştirilebilir isim gravürlü bebek künyesi.",
    description: "Bebeğinizin adını ve doğum tarihini sonsuza taşıyacak 14 ayar altın künye. İnce oval form, kadifemsi mat yüzey ve gravür detaylarıyla sade ama kalıcı bir hatıra. İsim ve tarih özelleştirmesi ücretsizdir.",
    images: [
      { src: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&fit=crop", alt: "Altın bebek künyesi düz" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Özelleştirme", value: "Ücretsiz İsim & Tarih Gravürü" }],
    karatDetails: [
      { label: "Metal", value: "585 Sarı Altın (14K)" },
      { label: "Boyut", value: "25 × 14 mm" },
    ],
    materials: ["14K Sarı Altın"],
    isNew: true,
  },
  {
    id: "bebek-kunye-002",
    slug: "altin-bebek-kunye-kalpli",
    name: "Altın Bebek Künyesi — Kalpli",
    category: "Bebek Künye",
    categorySlug: "bebek-ozel",
    tags: ["kunye"],
    price: 10500,
    priceFormatted: "₺10.500",
    shortDescription: "14 ayar rose altın, kalp motifli kişiselleştirilebilir bebek künyesi.",
    description: "Kalp formuyla sevgiyi simgeleyen bu künye, bebeğinizin boynunu zarif bir dokunuşla taçlandırır. Rose altının sıcaklığı ve lazer gravür teknolojisiyle hazırlanan kişisel yazı, onu benzersiz kılar.",
    images: [
      { src: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&fit=crop", alt: "Altın bebek künyesi kalpli" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Özelleştirme", value: "Ücretsiz Lazer Gravür" }],
    karatDetails: [
      { label: "Metal", value: "585 Rose Altın (14K)" },
      { label: "Boyut", value: "22 × 22 mm (kalp)" },
    ],
    materials: ["14K Rose Altın"],
    isNew: true,
  },
  {
    id: "bebek-kunye-003",
    slug: "altin-bebek-kunye-madalyon",
    name: "Altın Bebek Künyesi — Madalyon",
    category: "Bebek Künye",
    categorySlug: "bebek-ozel",
    tags: ["kunye"],
    price: 16800,
    priceFormatted: "₺16.800",
    shortDescription: "18 ayar altın, açılabilir madalyon künye; içine fotoğraf koyulabilir.",
    description: "İçi açılan madalyon formuyla hem künye hem fotoğraflık. Ön yüze isim-tarih, iç tarafa minik bir fotoğraf yerleştirilebilir. 18 ayar sarı altının sıcaklığı, anılarınızı kalıcı kılar.",
    images: [
      { src: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80&fit=crop", alt: "Altın bebek künyesi madalyon" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Özelleştirme", value: "Gravür + Fotoğraf Yuvası" }],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
      { label: "Boyut", value: "28 × 28 mm (yuvarlak)" },
    ],
    materials: ["18K Sarı Altın"],
    isNew: true,
  },

  // ── Bebek Özel — İğne ────────────────────────────────────────
  {
    id: "bebek-igne-001",
    slug: "altin-bebek-igne-nazar",
    name: "Altın Bebek İğnesi — Nazar",
    category: "Bebek İğne",
    categorySlug: "bebek-ozel",
    tags: ["igne"],
    price: 5400,
    priceFormatted: "₺5.400",
    shortDescription: "14 ayar altın, mavi mine nazar boncuklu bebek iğnesi.",
    description: "Gelenekten gelen nazar boncuğu motifi, 14 ayar altın çerçeve ve el boyaması mavi mine ile hayat buluyor. Bebeğinizin kıyafetine ya da battaniyesine güzellik ve koruma katacak minik bir tılsım.",
    images: [
      { src: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80&fit=crop", alt: "Altın bebek iğnesi nazar" },
    ],
    stoneSpecs: [
      { label: "Taş", value: "El Boyaması Mavi Mine" },
    ],
    certificateInfo: [{ label: "Kapama", value: "Güvenli Emniyet Klipsi" }],
    karatDetails: [
      { label: "Metal", value: "585 Sarı Altın (14K)" },
      { label: "Uzunluk", value: "3,5 cm" },
    ],
    materials: ["14K Sarı Altın", "Mine"],
    isNew: true,
  },
  {
    id: "bebek-igne-002",
    slug: "altin-bebek-igne-at-nali",
    name: "Altın Bebek İğnesi — At Nalı",
    category: "Bebek İğne",
    categorySlug: "bebek-ozel",
    tags: ["igne"],
    price: 6200,
    priceFormatted: "₺6.200",
    shortDescription: "14 ayar altın, şans motifli at nalı bebek iğnesi.",
    description: "At nalı, dünya genelinde şans ve koruma simgesi olarak kabul görür. 14 ayar sarı altından döküm tekniğiyle üretilen bu iğne; doğum hediyesi olarak da mükemmeldir.",
    images: [
      { src: "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&q=80&fit=crop", alt: "Altın bebek iğnesi at nalı" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Kapama", value: "Güvenli Emniyet Klipsi" }],
    karatDetails: [
      { label: "Metal", value: "585 Sarı Altın (14K)" },
      { label: "Uzunluk", value: "4 cm" },
    ],
    materials: ["14K Sarı Altın"],
    isNew: true,
  },
  {
    id: "bebek-igne-003",
    slug: "altin-bebek-igne-yildiz",
    name: "Altın Bebek İğnesi — Yıldız",
    category: "Bebek İğne",
    categorySlug: "bebek-ozel",
    tags: ["igne"],
    price: 7100,
    priceFormatted: "₺7.100",
    shortDescription: "18 ayar altın, pırlanta taşlı yıldız motifli bebek iğnesi.",
    description: "Bebeğiniz sizin için parlayan yıldız. 18 ayar beyaz altın üzerinde tek pırlanta taşlı, beş kollu yıldız formu. Hem sofistike hem de sevimli.",
    images: [
      { src: "https://images.unsplash.com/photo-1573408301185-9519f94f1b8f?w=800&q=80&fit=crop", alt: "Altın bebek iğnesi yıldız" },
    ],
    stoneSpecs: [
      { label: "Taş", value: "Doğal Pırlanta" },
      { label: "Karat", value: "0,05 ct" },
    ],
    certificateInfo: [{ label: "Kapama", value: "Güvenli Emniyet Klipsi" }],
    karatDetails: [
      { label: "Metal", value: "750 Beyaz Altın (18K)" },
      { label: "Uzunluk", value: "4 cm" },
    ],
    materials: ["18K Beyaz Altın", "Pırlanta"],
    isNew: true,
  },

  // ── Bebek Özel — Bileklik ────────────────────────────────────
  {
    id: "bebek-bileklik-001",
    slug: "altin-bebek-bileklik-zincir",
    name: "Altın Bebek Bilekliği — Zincir",
    category: "Bebek Bileklik",
    categorySlug: "bebek-ozel",
    tags: ["bileklik"],
    price: 9600,
    priceFormatted: "₺9.600",
    shortDescription: "14 ayar altın, kelebek kilit zincir bebek bilekliği.",
    description: "Bebek bileği için özel ölçülerde üretilen ince zincir bileklik. Kelebek formlu güvenli kilit sistemi, takıp çıkarmayı kolaylaştırır. Uzayabilen zincir özelliğiyle büyüdükçe kullanılabilir.",
    images: [
      { src: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80&fit=crop", alt: "Altın bebek bilekliği zincir" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Güvenlik", value: "Emniyet Kilidi" }],
    karatDetails: [
      { label: "Metal", value: "585 Sarı Altın (14K)" },
      { label: "Uzunluk", value: "10–13 cm (ayarlı)" },
    ],
    materials: ["14K Sarı Altın"],
    isNew: true,
  },
  {
    id: "bebek-bileklik-002",
    slug: "altin-bebek-bileklik-kalp",
    name: "Altın Bebek Bilekliği — Kalpli",
    category: "Bebek Bileklik",
    categorySlug: "bebek-ozel",
    tags: ["bileklik"],
    price: 11200,
    priceFormatted: "₺11.200",
    shortDescription: "14 ayar rose altın, kalp sallantılı bebek bilekliği.",
    description: "Minik kalp sallantısı ile her harekette sevgi fısıldar. Rose altının pembe tonları bebek koleksiyonuyla kusursuz uyum sağlar. Gravür ile kişiselleştirilebilir.",
    images: [
      { src: "https://images.unsplash.com/photo-1573408301185-9519f94f1b8f?w=800&q=80&fit=crop", alt: "Altın bebek bilekliği kalpli" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Güvenlik", value: "Emniyet Kilidi" }],
    karatDetails: [
      { label: "Metal", value: "585 Rose Altın (14K)" },
      { label: "Uzunluk", value: "10–13 cm (ayarlı)" },
    ],
    materials: ["14K Rose Altın"],
    isNew: true,
  },
  {
    id: "bebek-bileklik-003",
    slug: "altin-bebek-bileklik-pırlanta",
    name: "Altın Bebek Bilekliği — Pırlanta",
    category: "Bebek Bileklik",
    categorySlug: "bebek-ozel",
    tags: ["bileklik"],
    price: 19500,
    priceFormatted: "₺19.500",
    shortDescription: "18 ayar beyaz altın, tek pırlanta taşlı bebek bilekliği.",
    description: "Minik bir yıldızı bileğinize bağlayan bu bileklik, bebeğinizin büyüme yolculuğunun işareti olacak. 18 ayar beyaz altın üzeri tek pırlanta taşı, sade ama son derece etkileyici.",
    images: [
      { src: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80&fit=crop", alt: "Altın bebek bilekliği pırlanta" },
    ],
    stoneSpecs: [
      { label: "Taş", value: "Doğal Pırlanta" },
      { label: "Karat", value: "0,05 ct" },
    ],
    certificateInfo: [{ label: "Güvenlik", value: "Emniyet Kilidi" }],
    karatDetails: [
      { label: "Metal", value: "750 Beyaz Altın (18K)" },
      { label: "Uzunluk", value: "10–13 cm (ayarlı)" },
    ],
    materials: ["18K Beyaz Altın", "Pırlanta"],
    isNew: true,
  },

  // ── Bebek Özel — Kolye ────────────────────────────────────────
  {
    id: "bebek-kolye-001",
    slug: "altin-bebek-kolye-kalp",
    name: "Altın Bebek Kolyesi — Kalp",
    category: "Bebek Kolye",
    categorySlug: "bebek-ozel",
    tags: ["kolye"],
    price: 8800,
    priceFormatted: "₺8.800",
    shortDescription: "14 ayar rose altın, kalp sallantılı bebek kolyesi.",
    description: "Anne sevgisini bebeğin boynuna taşıyan ince zincir kolye. Küçük kalp sallantısı, her harekette sevgiyi hatırlatır. Uzayabilen zincir ile büyüdükçe kullanılabilir.",
    images: [
      { src: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80&fit=crop", alt: "Altın bebek kolyesi kalp" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Güvenlik", value: "Emniyet Kilidi" }],
    karatDetails: [
      { label: "Metal", value: "585 Rose Altın (14K)" },
      { label: "Uzunluk", value: "32–38 cm (ayarlı)" },
    ],
    materials: ["14K Rose Altın"],
    isNew: true,
  },
  {
    id: "bebek-kolye-002",
    slug: "altin-bebek-kolye-melek",
    name: "Altın Bebek Kolyesi — Melek",
    category: "Bebek Kolye",
    categorySlug: "bebek-ozel",
    tags: ["kolye"],
    price: 12400,
    priceFormatted: "₺12.400",
    shortDescription: "14 ayar altın, melek kanadı sallantılı bebek kolyesi.",
    description: "Melek kanatları bebeğinizi her zaman koruyacak. İnce çift zincir üzerinde asılı duran minyatür kanat sallantısı, 14 ayar sarı altının sıcaklığıyla bütünleşir.",
    images: [
      { src: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=80&fit=crop", alt: "Altın bebek kolyesi melek" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Güvenlik", value: "Emniyet Kilidi" }],
    karatDetails: [
      { label: "Metal", value: "585 Sarı Altın (14K)" },
      { label: "Uzunluk", value: "32–38 cm (ayarlı)" },
    ],
    materials: ["14K Sarı Altın"],
    isNew: true,
  },
  {
    id: "bebek-kolye-003",
    slug: "altin-bebek-kolye-ay-yildiz",
    name: "Altın Bebek Kolyesi — Ay Yıldız",
    category: "Bebek Kolye",
    categorySlug: "bebek-ozel",
    tags: ["kolye"],
    price: 15600,
    priceFormatted: "₺15.600",
    shortDescription: "18 ayar altın, pırlanta taşlı ay ve yıldız sallantılı bebek kolyesi.",
    description: "Ay ve yıldız, Türk kültüründe derin anlam taşır. 18 ayar sarı altın üzeri küçük pırlanta işlemeli bu sallantı, bebeğinizi hem gelenekle hem de lüksle buluşturur.",
    images: [
      { src: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80&fit=crop", alt: "Altın bebek kolyesi ay yıldız" },
    ],
    stoneSpecs: [
      { label: "Taş", value: "Doğal Pırlanta" },
    ],
    certificateInfo: [{ label: "Güvenlik", value: "Emniyet Kilidi" }],
    karatDetails: [
      { label: "Metal", value: "750 Sarı Altın (18K)" },
      { label: "Uzunluk", value: "32–38 cm (ayarlı)" },
    ],
    materials: ["18K Sarı Altın", "Pırlanta"],
    isNew: true,
  },

  // ── Bebek Özel — Yüzük ────────────────────────────────────────
  {
    id: "bebek-yuzuk-001",
    slug: "altin-bebek-yuzuk-duz",
    name: "Altın Bebek Yüzüğü — Düz",
    category: "Bebek Yüzük",
    categorySlug: "bebek-ozel",
    tags: ["yuzuk"],
    price: 7200,
    priceFormatted: "₺7.200",
    shortDescription: "14 ayar sarı altın, mat yüzeyli düz bebek yüzüğü.",
    description: "En sade olanın en güzel olduğunu hatırlatan yüzük. 14 ayar sarı altının kadifemsi mat yüzeyi, minik parmağa tam uyum sağlar. İsteğe göre isim gravürü eklenebilir.",
    images: [
      { src: "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&q=80&fit=crop", alt: "Altın bebek yüzüğü düz" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Ölçü", value: "8–10 numara (bebek)" }],
    karatDetails: [
      { label: "Metal", value: "585 Sarı Altın (14K)" },
      { label: "Bant Genişliği", value: "2 mm" },
    ],
    materials: ["14K Sarı Altın"],
    isNew: true,
  },
  {
    id: "bebek-yuzuk-002",
    slug: "altin-bebek-yuzuk-tasli",
    name: "Altın Bebek Yüzüğü — Taşlı",
    category: "Bebek Yüzük",
    categorySlug: "bebek-ozel",
    tags: ["yuzuk"],
    price: 9800,
    priceFormatted: "₺9.800",
    shortDescription: "14 ayar rose altın, tek taşlı bebek yüzüğü.",
    description: "Minik bir taş, büyük bir sevgi. Rose altın bant üzerinde tek renkli doğal taş. Doğum ayı taşı ile kişiselleştirilebilir, onu gerçekten ona özel kılar.",
    images: [
      { src: "https://images.unsplash.com/photo-1590080876351-941da357a4e4?w=800&q=80&fit=crop", alt: "Altın bebek yüzüğü taşlı" },
    ],
    stoneSpecs: [
      { label: "Taş", value: "Doğum Ayı Taşı (seçilebilir)" },
    ],
    certificateInfo: [{ label: "Ölçü", value: "8–10 numara (bebek)" }],
    karatDetails: [
      { label: "Metal", value: "585 Rose Altın (14K)" },
      { label: "Bant Genişliği", value: "2 mm" },
    ],
    materials: ["14K Rose Altın", "Doğum Taşı"],
    isNew: true,
  },
  {
    id: "bebek-yuzuk-003",
    slug: "altin-bebek-yuzuk-kalp",
    name: "Altın Bebek Yüzüğü — Kalpli",
    category: "Bebek Yüzük",
    categorySlug: "bebek-ozel",
    tags: ["yuzuk"],
    price: 8500,
    priceFormatted: "₺8.500",
    shortDescription: "14 ayar altın, kalp motifli bebek yüzüğü.",
    description: "Bebeğinizin parmağındaki küçük kalp, büyüdüğünde hatırlayacağı en güzel mücevheri olacak. İnce band üzerinde kabartmalı kalp motifi; sevgiyi, ilk anları ve sizi taşır.",
    images: [
      { src: "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800&q=80&fit=crop", alt: "Altın bebek yüzüğü kalpli" },
    ],
    stoneSpecs: [],
    certificateInfo: [{ label: "Ölçü", value: "8–10 numara (bebek)" }],
    karatDetails: [
      { label: "Metal", value: "585 Sarı Altın (14K)" },
      { label: "Bant Genişliği", value: "2,5 mm" },
    ],
    materials: ["14K Sarı Altın"],
    isNew: true,
  },
];

// Helpers
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getExclusiveProducts(): Product[] {
  return products.filter((p) => p.isExclusive);
}

export function getRelatedProducts(current: Product, count = 3): Product[] {
  const sameCategory = products.filter(
    (p) => p.categorySlug === current.categorySlug && p.id !== current.id && !p.isExclusive
  );
  const others = products.filter(
    (p) => p.categorySlug !== current.categorySlug && p.id !== current.id && !p.isExclusive
  );
  return [...sameCategory, ...others].slice(0, count);
}

export const categories = [
  { label: "Tümü", slug: "tumu" },
  { label: "Yüzükler", slug: "halkalar" },
  { label: "Kolyeler", slug: "kolyeler" },
  { label: "Bileklikler", slug: "bileklikler" },
  { label: "Küpeler", slug: "kupeler" },
  { label: "İnci", slug: "inci" },
  { label: "Setler", slug: "setler" },
];
